sudo: required

language: sh

services:
  - docker

before_install:
  - DOCKER_BASE="$DOCKER_USERNAME/jq-api"
  - DOCKER_BUILDS=""
  - TAGS=""
  - test "$TRAVIS_BRANCH" = master && TAGS="$TAGS latest" || true
  - test -n "$TRAVIS_TAG"          && TAGS="$TAGS stable $TRAVIS_TAG" || true
  - echo "Tags are $TAGS"

script:
  - docker build -t "$DOCKER_BASE:current" .
  - name="$DOCKER_BASE"
  - DOCKER_BUILDS="$DOCKER_BUILDS $name"

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - for repo in $DOCKER_BUILDS;
    do
      for tag in $TAGS;
      do
        echo "Deploying $repo:current as $repo:$tag...";
        docker tag "$repo:current" "$repo:$tag" || exit 1;
        docker push "$repo:$tag" || exit 1;
      done;
    done;